language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

install:
  - ./thinkphp/tests/script/install.sh

script:
  ## LINT
  - find thinkphp ! -path "thinkphp/vendor/*" -type f -name \*.php -exec php -l {} \;
  ## PHP_CodeSniffer
  - thinkphp/vendor/bin/phpcs --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 --standard=PSR2 --ignore="thinkphp/vendor/*" thinkphp
  ## PHP Copy/Paste Detector
  - thinkphp/vendor/bin/phpcpd --verbose --exclude vendor thinkphp || true
  ## PHPLOC
  - thinkphp/vendor/bin/phploc --exclude vendor thinkphp
  ## PHPUNIT
  - thinkphp/vendor/bin/phpunit --coverage-clover=coverage.xml --configuration=thinkphp/phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
